In [16]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [26]:
encounters = pd.read_csv("../data/encounters.csv")
payers = pd.read_csv("../data/payers.csv")
patients = pd.read_csv("../data/patients.csv")
claims = pd.read_csv("../data/claims.csv")

In [28]:
encounters.head(3)

,Id,START,STOP,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
0,748f8357-6cc7-551d-f31a-32fa2cf84126,2019-02-17T05:07:38Z,2019-02-17T05:22:38Z,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,f7ae497d-8dc6-3721-9402-43b621a4e7d2,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,877.79,833.90,NaN,NaN
1,5a4735ae-423f-6563-28ab-b3d11b49b2d4,2019-03-24T05:07:38Z,2019-03-24T05:22:38Z,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,f7ae497d-8dc6-3721-9402-43b621a4e7d2,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,269.68,256.20,NaN,NaN
2,0bee1ce6-3e2c-5506-f71c-a7ba8f64a3d3,2019-05-26T05:07:38Z,2019-05-26T05:22:38Z,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,f7ae497d-8dc6-3721-9402-43b621a4e7d2,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,1292.75,1228.11,NaN,NaN

In [32]:
encounters

,Id,START,STOP,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
0,748f8357-6cc7-551d-f31a-32fa2cf84126,2019-02-17T05:07:38Z,2019-02-17T05:22:38Z,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,f7ae497d-8dc6-3721-9402-43b621a4e7d2,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,877.79,833.90,NaN,NaN
1,5a4735ae-423f-6563-28ab-b3d11b49b2d4,2019-03-24T05:07:38Z,2019-03-24T05:22:38Z,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,f7ae497d-8dc6-3721-9402-43b621a4e7d2,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,269.68,256.20,NaN,NaN
2,0bee1ce6-3e2c-5506-f71c-a7ba8f64a3d3,2019-05-26T05:07:38Z,2019-05-26T05:22:38Z,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,f7ae497d-8dc6-3721-9402-43b621a4e7d2,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,1292.75,1228.11,NaN,NaN
3,6e93bcf9-45a4-8528-0120-1c1eaa930faf,2019-07-28T05:07:38Z,2019-07-28T05:22:38Z,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,f7ae497d-8dc6-3721-9402-43b621a4e7d2,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,1323.87,1257.68,NaN,NaN
4,8b6787c3-4316-a0cb-899d-4746525c319f,2019-10-27T05:07:38Z,2019-10-27T05:22:38Z,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,f7ae497d-8dc6-3721-9402-43b621a4e7d2,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,831.76,790.17,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61454,230e2215-38ab-9371-842d-a44d27ae4090,2020-12-18T05:11:58Z,2020-12-18T05:26:58Z,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,4861d01f-019c-3dac-a153-8334e50919f9,b0c5743a-4f9a-33b3-bab4-6a474fcf9ffd,d47b3510-2895-3b70-9897-342d681c769d,ambulatory,390906007,Follow-up encounter,77.49,77.49,0.00,55822004.0,Hyperlipidemia
61455,db101ad8-66e2-9feb-e0cf-b2618f873c3a,2020-12-28T02:11:58Z,2020-12-28T02:26:58Z,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,4861d01f-019c-3dac-a153-8334e50919f9,b0c5743a-4f9a-33b3-bab4-6a474fcf9ffd,d47b3510-2895-3b70-9897-342d681c769d,ambulatory,185345009,Encounter for symptom,77.49,77.49,0.00,38822007.0,Cystitis
61456,1516d2e6-4846-5f1e-fe27-c1ebb9a39f72,2021-01-15T05:11:58Z,2021-01-15T05:26:58Z,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,cd300275-3f4d-3adb-98aa-4e5bba25be24,7cd691a9-0e34-351a-918d-af3f6d3c0279,d47b3510-2895-3b70-9897-342d681c769d,wellness,162673000,General examination of patient (procedure),129.16,786.33,0.00,NaN,NaN
61457,b2a4d90b-a2f5-1c88-0fb6-ba49b1487d37,2021-08-13T05:11:58Z,2021-08-13T05:26:58Z,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,4861d01f-019c-3dac-a153-8334e50919f9,b0c5743a-4f9a-33b3-bab4-6a474fcf9ffd,d47b3510-2895-3b70-9897-342d681c769d,outpatient,33879002,Administration of vaccine to produce active im...,129.16,269.68,0.00,NaN,NaN
61458,0732798b-fb31-183b-22b6-efb205ee6502,2021-09-03T05:11:58Z,2021-09-03T05:26:58Z,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,4861d01f-019c-3dac-a153-8334e50919f9,b0c5743a-4f9a-33b3-bab4-6a474fcf9ffd,d47b3510-2895-3b70-9897-342d681c769d,outpatient,33879002,Administration of vaccine to produce active im...,129.16,269.68,0.00,NaN,NaN

In [12]:
payers.head(2)

,Id,NAME,ADDRESS,CITY,STATE_HEADQUARTERED,ZIP,PHONE,AMOUNT_COVERED,AMOUNT_UNCOVERED,REVENUE,...,UNCOVERED_ENCOUNTERS,COVERED_MEDICATIONS,UNCOVERED_MEDICATIONS,COVERED_PROCEDURES,UNCOVERED_PROCEDURES,COVERED_IMMUNIZATIONS,UNCOVERED_IMMUNIZATIONS,UNIQUE_CUSTOMERS,QOLS_AVG,MEMBER_MONTHS
0,b3221cfc-24fb-339e-823d-bc4136cbc4ed,Dual Eligible,7500 Security Blvd,Baltimore,MD,21244.0,1-877-267-2323,2786029.66,358233.14,1439000.0,...,0,1141,0,551,0,280,0,20,0.537055,3060
1,7caa7254-5050-3b5e-9eae-bd5ea30e809c,Medicare,7500 Security Blvd,Baltimore,MD,21244.0,1-800-633-4227,36196594.58,2549080.77,7513750.0,...,0,10455,0,6957,0,3057,0,195,0.766254,30888

In [17]:
patients.head(3)

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,SUFFIX,MAIDEN,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE
0,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,2019-02-17,NaN,999-65-3251,NaN,NaN,NaN,Damon455,Langosh790,NaN,NaN,NaN,white,nonhispanic,M,Middleborough Massachusetts US,620 Lynch Tunnel Apt 0,Springfield,Massachusetts,Hampden County,1104.0,42.080389,-72.480431,9039.1645,7964.1255
1,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,2005-07-04,NaN,999-49-3323,S99941126,NaN,NaN,Thi53,Wunsch504,NaN,NaN,NaN,white,nonhispanic,F,Danvers Massachusetts US,972 Tillman Branch Suite 48,Bellingham,Massachusetts,Norfolk County,NaN,42.035213,-71.482519,402723.4150,14064.1350
2,339144f8-50e1-633e-a013-f361391c4cff,1998-05-11,NaN,999-10-8743,S99996708,X75063318X,Mr.,Chi716,Greenfelder433,NaN,NaN,NaN,white,nonhispanic,M,Athens Athens Prefecture GR,1060 Bernhard Crossroad Suite 15,Boston,Massachusetts,Suffolk County,2131.0,42.292557,-71.061160,571935.8725,787.5375

In [ ]:
patients["DEATHDATE"] = patients["DEATHDATE"].fillna("unknown")
patients["PASSPORT"] = patients["PASSPORT"].fillna("unknown")
patients["PASSPORT"] = patients["PASSPORT"].fillna("unknown")

In [43]:
patients["FIRST"] = patients["FIRST"].str.replace(r"\d+", "", regex=True)

0         Damon
1           Thi
2           Chi
3       Phillis
4       Jerrold
         ...
1158        Coy
1159     Sherry
1160      Vance
1161       Cody
1162    Haywood
Name: FIRST, Length: 1163, dtype: object

In [27]:
claims.head(3)

,Id,PATIENTID,PROVIDERID,PRIMARYPATIENTINSURANCEID,SECONDARYPATIENTINSURANCEID,DEPARTMENTID,PATIENTDEPARTMENTID,DIAGNOSIS1,DIAGNOSIS2,DIAGNOSIS3,DIAGNOSIS4,DIAGNOSIS5,DIAGNOSIS6,DIAGNOSIS7,DIAGNOSIS8,REFERRINGPROVIDERID,APPOINTMENTID,CURRENTILLNESSDATE,SERVICEDATE,SUPERVISINGPROVIDERID,STATUS1,STATUS2,STATUSP,OUTSTANDING1,OUTSTANDING2,OUTSTANDINGP,LASTBILLEDDATE1,LASTBILLEDDATE2,LASTBILLEDDATEP,HEALTHCARECLAIMTYPEID1,HEALTHCARECLAIMTYPEID2
0,e413105d-6f23-34ef-724a-b42adab9df22,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,0,10,10,410620009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,748f8357-6cc7-551d-f31a-32fa2cf84126,2019-02-17T05:07:38Z,2019-02-17T05:07:38Z,82608ebb-037c-3cef-9d34-3736d69b29e8,CLOSED,NaN,CLOSED,0.0,NaN,0.0,2019-02-17T05:22:38Z,NaN,2019-02-17T05:22:38Z,1,0
1,8e430d76-6628-c3ac-8950-2acabeb34f86,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,0,10,10,410620009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5a4735ae-423f-6563-28ab-b3d11b49b2d4,2019-03-24T05:07:38Z,2019-03-24T05:07:38Z,82608ebb-037c-3cef-9d34-3736d69b29e8,CLOSED,NaN,CLOSED,0.0,NaN,0.0,2019-03-24T05:22:38Z,NaN,2019-03-24T05:22:38Z,1,0
2,3a69d5f0-26d8-fe66-4a1b-1a7c9ab618c8,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,0,10,10,410620009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0bee1ce6-3e2c-5506-f71c-a7ba8f64a3d3,2019-05-26T05:07:38Z,2019-05-26T05:07:38Z,82608ebb-037c-3cef-9d34-3736d69b29e8,CLOSED,NaN,CLOSED,0.0,NaN,0.0,2019-05-26T05:22:38Z,NaN,2019-05-26T05:22:38Z,1,0

In [60]:
from pathlib import Path

path = Path("../patients.csv")

print(path.resolve())
print(path.exists())

C:\Users\Bagdo\Documents\AirflowPractise\Patients_Enrollment\patients.csv
True

In [61]:
check = pd.read_csv(path)

In [62]:
check

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,SUFFIX,MAIDEN,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,HAS_INVALID_NAME
0,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,2019-02-17,NaN,999-65-3251,UNKNOWN,UNKNOWN,NaN,Damon,Langosh,NaN,NaN,NaN,white,nonhispanic,M,Middleborough Massachusetts US,620 Lynch Tunnel Apt 0,Springfield,Massachusetts,Hampden County,1104.0,42.080389,-72.480431,9.039165e+03,7964.1255,False
1,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,2005-07-04,NaN,999-49-3323,S99941126,UNKNOWN,NaN,Thi,Wunsch,NaN,NaN,NaN,white,nonhispanic,F,Danvers Massachusetts US,972 Tillman Branch Suite 48,Bellingham,Massachusetts,Norfolk County,NaN,42.035213,-71.482519,4.027234e+05,14064.1350,False
2,339144f8-50e1-633e-a013-f361391c4cff,1998-05-11,NaN,999-10-8743,S99996708,X75063318X,Mr.,Chi,Greenfelder,NaN,NaN,NaN,white,nonhispanic,M,Athens Athens Prefecture GR,1060 Bernhard Crossroad Suite 15,Boston,Massachusetts,Suffolk County,2131.0,42.292557,-71.061160,5.719359e+05,787.5375,False
3,d488232e-bf14-4bed-08c0-a82f34b6a197,2003-01-28,NaN,999-56-6057,S99929424,UNKNOWN,Ms.,Phillis,Walter,NaN,NaN,NaN,white,nonhispanic,F,Boston Massachusetts US,677 Ritchie Terrace,Hingham,Massachusetts,Plymouth County,2043.0,42.200491,-70.916076,5.825578e+05,104782.2070,False
4,217f95a3-4e10-bd5d-fb67-0cfb5e8ba075,1993-12-23,NaN,999-91-4320,S99991143,X44132498X,Mr.,Jerrold,Herzog,NaN,NaN,M,black,nonhispanic,M,Boston Massachusetts US,276 Bernier Branch,Revere,Massachusetts,Suffolk County,NaN,42.381875,-70.999286,4.758269e+05,18067.0950,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1158,409330fa-7ffd-dbfb-4eba-2349d58a6324,1979-02-28,NaN,999-68-5445,S99991649,X72884711X,Mr.,Coy,Schaden,NaN,NaN,M,white,nonhispanic,M,Fitchburg Massachusetts US,434 Hickle Throughway Suite 15,Amherst,Massachusetts,Hampshire County,NaN,42.380084,-72.527376,1.050937e+06,346.5075,False
1159,cb328021-a854-dc94-e7ae-426580477308,1964-05-31,NaN,999-10-6445,S99986790,X86596484X,Mrs.,Sherry,Barrows,NaN,Schuppe920,M,white,nonhispanic,F,Boston Massachusetts US,976 Ortiz Orchard,Stoughton,Massachusetts,Norfolk County,NaN,42.081223,-71.126028,8.031471e+05,553335.4420,False
1160,41862157-5c14-f706-4a94-d2929be969e7,1967-07-12,NaN,999-63-2407,S99976335,X68999803X,Mr.,Vance,Jakubowski,NaN,NaN,M,asian,nonhispanic,M,Brockton Massachusetts US,534 Strosin Corner,Gardner,Massachusetts,Worcester County,1440.0,42.604215,-72.013243,1.028321e+06,28607.5050,False
1161,d53c57a5-4480-2481-32ee-b2844a991c9d,1948-07-28,NaN,999-37-8036,S99939062,X79037907X,Mr.,Cody,Hilll,NaN,NaN,M,white,nonhispanic,M,Stoneham Massachusetts US,568 Ryan Stravenue,Mashpee,Massachusetts,Barnstable County,NaN,41.577704,-70.507460,2.638801e+05,155042.0520,False
1162,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,1958-11-07,NaN,999-17-1411,S99963285,X2822177X,Mr.,Haywood,Schroeder,NaN,NaN,M,asian,nonhispanic,M,Peabody Massachusetts US,707 Heathcote Wall Suite 15,Marblehead,Massachusetts,Essex County,NaN,42.466700,-70.903323,1.548721e+06,217.1100,False